rhel-labs/learn-katacoda

- .gitignore
- environments/rhel8/build/2_configure-standalone.sh
- environments/rhel8/build/3_packages.sh
Here is the base configuration used. 
Feel free to add packages to the list in 3_package.sh
If you need something more focused, such as downloading container images, please add a new file such as 4_pull.sh to help keep the scripts maintainable.
> Initial environment

- branded-ui/katacoda/templates/scenario.html
- branded-ui/katacoda/templates/training-scenario.html
Switch to using Red instead of Grey
> Wrong colours

- imagebuilder/step10.md
- imagebuilder/step2.md
- imagebuilder/step3.md
- imagebuilder/step4.md
- imagebuilder/step5.md
- imagebuilder/step6.md
- imagebuilder/step7.md
- imagebuilder/step8.md
- imagebuilder/step9.md
These steps made the demo longer than it needed to be.
And this can be done at step 0 with the commands that
are predefined.
> Removes the two extra steps for modifying user account

- appstream-manage/step5.md
- branded-ui/katacoda/templates/scenario.html
- branded-ui/katacoda/templates/training-scenario.html
- environments/rhel8/build/3_packages.sh
- podman-deploy/index.json
- podman-deploy/step2.md
- podman-deploy/step3.md
- podman-deploy/step4.md
- podman-deploy/step5.md
1) Cockpit is enabled by default in the environment. This should make it faster to boot.
2) I had to change Podman as it was using Terminal/Terminal but we haven't got that working with a single host yet.
> Pre Summit v1 Changes

- environments/rhel8/build/1_enablerepos.sh
- environments/rhel8/build/3_packages.sh
Not sure of the name for ansible-2.8-for-rhel-8-x86_64-rpms
> Presummitv4

- buildah/background.sh
- buildah/index.json
- buildah/intro.md
- buildah/step1.md
- buildah/step2.md
First pass at buildah scenario, only two steps to verify functionality.  Will clean up into multiple steps and remove unneeded output.
> Initial buildah scenario creation

- buildah/index.json
Forgot to remove steps from template
> Remove missing steps from index

- buildah/background.sh
- buildah/step1.md
- buildah/step2.md
Add variable to capture mount point for reuse
Switch to public UBI container for base
> Fix mount capture, use the right container, minor clean up

- buildah/index.html
- buildah/index.json
- buildah/step1.md
- buildah/step2.md
Removed some long output
Added new index.html creation and container service dashboard
> Clean up output (pass 1), add web service console and new index copy

- buildah/index.json
> I hate JSON

- buildah/index.json
- buildah/intro.md
- buildah/step1.md
- buildah/step2.md
- buildah/step3.md
- buildah/step4.md
Now 4 steps, build vs run
Addressed prose and style issues
> Cleaned up prose, broke into multiple steps

- scenario-template/index.json
- scenario-template/step1.md
- scenario-template/step2.md
- scenario-template/step3.md
- scenario-template/step4.md
- scenario-template/step5.md
Reorder index.json to show environmentals first, then steps
Added example of multiple file copy to index.json
Added iframe layout example for web consoles
> Scenario template

- buildah/assets/index1.html
- buildah/assets/index2.html
- buildah/index.json
- buildah/step1.md
- buildah/step2.md
- buildah/step3.md
- buildah/step4.md
Scenario is working as intended and ready for review
> Merge final fixes for buildah scenario

- podman-deploy-jp/index.json
- podman-deploy-jp/intro.md
- podman-deploy-jp/step1.md
- podman-deploy-jp/step2.md
- podman-deploy-jp/step3.md
- podman-deploy-jp/step4.md
- podman-deploy-jp/step5.md
> podman-deploy Japanese translation

- webconsole-software-jp/index.json
- webconsole-software-jp/intro.md
- webconsole-software-jp/step0.md
- webconsole-software-jp/step1.md
- webconsole-software-jp/step2.md
- webconsole-software-jp/step3.md
- webconsole-software-jp/step4.md
- webconsole-software-jp/step5.md
Japanese translation of webconsole-software
> webconsole-software-jp translation

- appstream-manage-jp/index.json
- appstream-manage-jp/intro.md
- appstream-manage-jp/step1.md
- appstream-manage-jp/step2.md
- appstream-manage-jp/step3.md
- appstream-manage-jp/step4.md
- appstream-manage-jp/step5.md
- appstream-manage-jp/step6.md
For your info, I kept 'Application Stream' as-is in this translation.
> application stream Japanese translation

- VDO-configure-jp/index.json
- appstream-manage-jp/index.json
- buildah-jp/index.json
- crypto-policy-jp/index.json
- podman-deploy-jp/index.json
- session-recording-tlog-jp/index.json
- webconsole-software-jp/index.json
Fix typo of my name by myself.
> fix my name Moriwaka

- training/workshop-jp-pathway.json
I'm sorry for bothering you. I fixed pathway_id to "rhel-labs".
> fix pathway_id

- ansible-example/intro.md
- ansible-example/step1.md
> syncing some READmes to see what happens

- ebpf-tracing/finish.md
- ebpf-tracing/index.json
- ebpf-tracing/step2.md
- ebpf-tracing/step3.md
- ebpf-tracing/step4.md
- ebpf-tracing/step5.md
- ebpf-tracing/step6.md
These updates:
- incorporate the style guide
- give the user more information about what they are doing and what they should inspect.
- hopefully split the steps in an appropriate manner.
> Updates to the BPF Lab from Karl

- ebpf-tracing/step3.md
- ebpf-tracing/step4.md
- ebpf-tracing/step6.md
This pr has a few minor typos fixed.
> Small changes

- ansible-example2/assets/ansible.cfg
- ansible-example2/assets/apache.yml
- ansible-example2/assets/hosts
- ansible-example2/assets/index.html
- ansible-example2/background.sh
- ansible-example2/index.json
- ansible-example2/intro.md
- ansible-example2/step1.md
- ansible-introduction/assets/config
- ansible-introduction/assets/hostname.yml
- ansible-introduction/assets/playbook.yml
- ansible-introduction/step5.md
- ansible-introduction/step6.md
- ansible-web-server/index.json
also trying to add back a legit ansible2-example and then nuke it
> adding step 6 to ansible introduction

- .gitignore
- ansible-introduction/step1.md
- ansible-introduction/step3.md
- ansible-web-server/assets/apache.yml
- ansible-web-server/index.json
- ansible-web-server/intro.md
- ansible-web-server/step1.md
- ansible-web-server/step2.md
- ansible-web-server/step3.md
- ansible-web-server/step4.md
- ansible-web-server/step5.md
- ansible-web-server/step6.md
all on Red Hat Enterprise Linux 8!
> fixing ansible-web-server

- ansible-introduction/background.sh
- ansible-introduction/foreground.sh
- ansible-introduction/index.json
- ansible-introduction/step1.md
- ansible-introduction/step2.md
- ansible-introduction/step3.md
- ansible-introduction/step4.md
- ansible-web-server/assets/config
- ansible-web-server/background.sh
- ansible-web-server/foreground.sh
- ansible-web-server/index.json
- ansible-web-server/step1.md
- ansible-web-server/step6.md
- sql-server-ansible/background.sh
addressing most issues brought up by the feedback in https://github.com/rhel-labs/learn-katacoda/issues/101 and copying the `foreground.sh` in the sql-server-ansible from @cloin
> exercises updates for ansible-introduction

- ansible-introduction/index.json
- ansible-introduction/step1.md
- ansible-web-server/assets/apache.yml
- ansible-web-server/index.json
- ansible-web-server/step2.md
- ansible-web-server/step6.md
- ansible-web-server/step7.md
adding multiple tabs as per issue https://github.com/rhel-labs/learn-katacoda/issues/101
> updating tabs and instructions for web servers

- ansible-introduction/index.json
- ansible-web-server/index.json
for some reason this is not working
> fixing terminals line

- stratis/finish.md
- stratis/index.json
- stratis/intro.md
- stratis/step1.md
- stratis/step2.md
- stratis/step3.md
- stratis/step4.md
- stratis/step5.md
- stratis/step6.md
- stratis/step7.md
- stratis/step8.md
Add a tutorial for using the Stratis CLI to manage local storage.
> Stratis tutorial

- branded-ui/katacoda/main.go
- branded-ui/katacoda/templates/index.html
This is already live. PR so changes are tracked.
> Force HTTPS 

- appstream-manage-jp/step1.md
append 'version 12' to sync with RHEL 8.1.
> append 'version 12' to appstream-manage-jp

- session-recording-tlog-jp/step2.md
- webconsole-software-jp/step1.md
Japanese translation of notes.
> [jp] add notes about web console in another window

- ebpf-tracing/step5.md
filetop man page says "Type of file: R == regular, S == socket, O == other (pipe, etc)."
> filetop T column

- ebpf-tracing/step3.md
align some filetop field descriptions to its man page.
> filetop fileld description

- kpatch-apply/step5.md
How about adding  link to Red Hat CVE Database?
> adding a link to CVE Database

- selinux-containers/step3.md
For step 3, indicate that `podman run`
is submitted in terminal 2. This is
consistent with how it is written
in step 1.
> Indicate which terminal is used

- networking-basics/finish.md
- networking-basics/index.json
- networking-basics/intro.md
- networking-basics/step1.md
- networking-basics/step2.md
- networking-basics/step3.md
- networking-basics/step4.md
- networking-basics/step5.md
Draft of the network configuration basics lab. All of the content is there and I have tested the command sequence in the Ansible lab environment and it appears they all work. After this is merged I will do testing and revisions as I am sure I made some mistakes somewhere.
> Networking basics first draft

- networking-basics/index.json
- networking-basics/intro.md
- networking-basics/step1.md
- networking-basics/step2.md
- networking-basics/step3.md
- networking-basics/step4.md
- networking-basics/step5.md
changed narrative order, fixed technical mistakes and typos
> First major revision

- file-permissions/index.json
- file-permissions/intro.md
- file-permissions/step1.md
- file-permissions/step2.md
- file-permissions/step3.md
- file-permissions/step4.md
- file-permissions/step5.md
- file-permissions/step6.md
- file-permissions/step7.md
added validation prints and fixed issues with logic
> File permissions testing edits

- file-permissions/step7.md
fixed bad formatting in step 7
> File permissions

- user-basics/finish.md
- user-basics/intro.md
- user-basics/step1.md
- user-basics/step3.md
- user-basics/step5.md
fixed cat piped into grep, used `groups` instead of `id`, updated __viewers__ gid to be 10000, replaced `chage` with `usermod -L` for acct lock, made `userdel` user `-r` option
> revisions from review w/ scott

- user-basics/step2.md
piped password into `passwd` with the `--stdin` option
> converted password configuration to be less interactive

- installing-software-yum/finish.md
- installing-software-yum/index.json
- installing-software-yum/intro.md
- installing-software-yum/step1.md
- installing-software-yum/step2.md
- installing-software-yum/step3.md
- installing-software-yum/step4.md
- installing-software-yum/step5.md
pushing to get live copy for proofreading
> Installing software with yum lab

- installing-software-yum/step2.md
- installing-software-yum/step3.md
changed package to one that needs update on new image
> updated outputs for 8.4

- crypto-policy-jp/index.json
didn't need to make any changes to the English version
> updated crypto-policy-jp to 8-4

- imagebuilder-cli/index.json
encountered unexpected error that completely blocked lab progress
```
[root@a74278ee424a ~]# composer-cli blueprints list
2021-06-17 18:09:09,048: /run/weldr/api.socket does not exist
```
Will continue to investigate
> reverting imagebuilder-cli update

- imagebuilder-cli/step4.md
linux partition is now 3 instead of 1
> updated mount index to be compatible with 8-4

- service-admin/index.json
> removed extraneous steps

- service-admin/finish.md
- service-admin/index.json
- service-admin/intro.md
- service-admin/step3.md
changed "process" to "service" in step 3, updated time estimate
> Proofreading changes

- service-admin/background.sh
- service-admin/finish.md
- service-admin/index.json
- service-admin/intro.md
- service-admin/step1.md
- service-admin/step2.md
- service-admin/step3.md
- service-admin/step4.md
- service-admin/step5.md
added process admin intro, reworded example to use NFS, improved lab pacing
> Service admin overhaul

- homepage-pathway.json
- service-admin/step1.md
- service-admin/step2.md
implemented suggestions to clear up process management section, added lab to homepage
> Service admin edits

- helpful-commands/index.json
- helpful-commands/step1.md
- helpful-commands/step2.md
- helpful-commands/step3.md
- helpful-commands/step4.md
- helpful-commands/step5.md
- helpful-commands/step6.md
- helpful-commands/step7.md
> Helpful commands testing revision

- helpful-commands/finish.md
- helpful-commands/intro.md
- helpful-commands/step1.md
- helpful-commands/step2.md
- helpful-commands/step3.md
- helpful-commands/step4.md
- helpful-commands/step6.md
- helpful-commands/step7.md
expanded content, fixed errors
> Helpful commands revisions

- nbde-introduction/background.sh
- nbde-introduction/step2.md
So that we can access it from other machines.
Resolves: #215
> nbde-introduction: include steps to open the tang port in the firewall
